org: vidyasravil
app: dealmgt
service: dealmgt
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DYNAMODB_DEAL_TABLE: "${self:service}-dealTable-${sls:stage}"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query" # Make sure to include this
      Resource:
        - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-dealTable-${sls:stage}"
        - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-dealTable-${sls:stage}/*" # This covers indexes

functions:
  createDeal:
    handler: deals/v1/createDeal.createDeal
    events:
      - httpApi:
          path: /v1/deals
          method: post
          authorizer:
            type: aws_iam
  getDeal:
    handler: deals/v1/getDeal.getDeal
    events:
      - httpApi:
          path: /v1/deals/{dealId}
          method: get
          authorizer:
            type: aws_iam
  updateDeal:
    handler: deals/v1/updateDeal.updateDeal
    events:
      - httpApi:
          path: /v1/deals/{dealId}
          method: put
          authorizer:
            type: aws_iam
  deleteDeal:
    handler: deals/v1/deleteDeal.deleteDeal
    events:
      - httpApi:
          path: /v1/deals/{dealId}
          method: delete
          authorizer:
            type: aws_iam
  getDealsByOwner:
    handler: deals/v1/getDealsByOwner.getDealsByOwner
    events:
      - httpApi:
          path: /v1/deals
          method: get
          authorizer:
            type: aws_iam

resources:
  Resources:
    DealTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
          - AttributeName: dealOwnerId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: DealOwnerIndex
            KeySchema:
              - AttributeName: dealOwnerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: "${self:service}-dealTable-${sls:stage}"
